export function c(...classNames) {
  return classNames
    .filter(v => v)
    .join(' ')
    .trim()
    .replace(/\s{2,}/g, ' ');
}

export const colors = [
  {
    'name': 'teal blue',
    'type': 'core',
    'hex': '2A7B88',
    'rgb': '42, 123, 136'
  },
  {
    'name': 'deep koamaru',
    'type': 'core',
    'hex': '3D315B',
    'rgb': '61, 49, 91'
  },
  {
    'name': 'jazzberry jam',
    'type': 'core',
    'hex': '991862',
    'rgb': '153, 24, 98'
  },
  {
    'name': 'independence',
    'type': 'core',
    'hex': '425569',
    'rgb': '66, 85, 105'
  },
  {
    'name': 'asparagus',
    'type': 'core',
    'hex': '7EA16B',
    'rgb': '126, 161, 107'
  },
  {
    'name': 'spanish pink',
    'type': 'accent',
    'hex': 'EBBAB9',
    'rgb': '235, 186, 185'
  },
  {
    'name': 'english vermillion',
    'type': 'accent',
    'hex': 'CC444B',
    'rgb': '204, 68, 75'
  },
  {
    'name': 'pastel blue',
    'type': 'accent',
    'hex': 'B0D0D3',
    'rgb': '176, 208, 211'
  },
  {
    'name': 'light apricot',
    'type': 'accent',
    'hex': 'FCD7AD',
    'rgb': '252, 215, 173'
  },
  {
    'name': 'deep saffron',
    'type': 'accent',
    'hex': 'FFA630',
    'rgb': '255, 166, 48'
  },
  {
    'name': 'birb blue',
    'type': 'variant',
    'hex': '1566B0',
    'rgb': '21, 102, 176'
  },
]

export const icebreakers = [
  'Do you love working from home or in the office? Is there a balance of both that you like best?',
  'Where do you work most frequently from at home? Your office? Your kitchen table? The backyard? Your bed?',
  'Can you give a tour of your office space? ?',
  'Be honest, how often do you work from bed?',
  'What does your morning routine look like when working from home?',
  'How many cups of coffee, tea, or beverage-of-choice do you have each morning?',
  'Do you have any pets as in-house colleagues?',
  'Do you have houseplants in your office? ?',
  'What’s your go-to remote work outfit? ?',
  'What animal represents you?',
  'What was your dream profession growing up?',
  'What is something you’ve always wanted to do but haven’t done yet?',
  'Do you have any family traditions that you look forward to each year?',
  'Would you like to be famous? In what way?',
  'What’s your dream car?',
  'Who in your life has inspired you most?',
  'If you weren’t in this career, what could you see yourself doing?',
  'What is one thing on the very top of your bucket list?',
  'If you’re not from this city, why did you end up here?',
  'What is your guilty pleasure?',
  'If you could change anything about the way you were raised, what would it be?',
  'What’s the craziest thing you have ever done?',
  'If you had a million dollars, what would be the first thing you bought?',
  'What’s your favorite thing about your job?',
  'What’s something you are really proud of accomplishing?',
  'What’s something interesting about your family history?',
  'When you’re not at work, what are your passions?',
  'Do you have siblings? How many? Where do you fit in the mix?',
  'What’s your biggest fear?',
  'What’s your secret talent?',
  'Who’s the most famous person you’ve ever met?',
  'What’s your favorite hobby?',
  'What clubs were you a member of in high school?',
  'Do you speak any languages besides English? Is there a reason you learned it?',
  'What’s your favorite childhood memory?',
  'What is your biggest pet peeve?',
  'Name three things you and your partner have in common.?',
  'What’s your most treasured memory?',
  'For what in your life do you feel most grateful?',
  'If you could pick up a new skill in an instant what would it be?',
  'What would you like to be known or remembered for?',
  'What would your dream house be like?',
  'What sport would you compete in if you were in the Olympics?',
  'Do you collect anything?',
  'If you could instantly become an expert in something, what would it be?',
  'Who’s someone you really admire?',
  'What’s your favorite quote?',
  'What’s your favorite boardgame?',
  'What’s something you love that people wouldn’t expect?',
  'What fictional family would you be a member of?',
  'What was the worst job you ever had?',
  'If you could change places with anyone in the world, who would it be and why?',
  'If you could eliminate one thing from your daily routine, what would it be and why?',
  'If you had to teach a class on one thing, what would you teach?',
  'If you could magically become fluent in any language, what would it be?',
  'Are you a morning person or a night person?',
  'Sweet or savory?',
  'Did you ever have an imaginary friend? If so, what was its name?',
  'What was your least favorite food as a child? Do you still hate it or do you love it now?',
  'If you were forced to sing karaoke, what song would you choose and why?',
  'What was your least favorite childhood chore and why?',
  'What’s your caffeinated beverage of choice? Coffee? Cola? Tea?',
  'What’s your favorite scent?',
  'What was the last thing you gave 100% to?',
  'If you could say one thing to the entire world right now, what would you say?',
  'Do you care about your astrological sign?',
  'What’s the last thing you got in “trouble” for? ?',
  'Do you have a favorite song to listen to when you need your spirits lifted?',
  'What is the most feel-good film you’ve ever seen?',
  'What type of music do you prefer?',
  'What’s your favorite TV show and why?',
  'Have you ever been in a movie, TV show, or play? What was your role?',
  'If you could hang out with any cartoon character, who would you choose and why?',
  'If you could be in any movie, what would it be and what character would you play?',
  'Which actor would you want to play you in the movie about your life?',
  'What book did you read that changed your life the most?',
  'If you could see one movie again for the first time, what would it be and why?',
  'You have your own late-night talk show. Who do you invite as your first guest?',
  'What would the title of your autobiography be?',
  'What was your favorite band ten years ago?',
  'If you could only listen to one song for the rest of your life, what would it be?',
  'If you could only watch one movie for the rest of your life, what would it be?',
  'What’s the greatest TV show ever made?',
  'What’s the worst TV show ever made?',
  'Do you watch any TV shows that you pretend you don’t watch when people ask?',
  'What was your favorite movie as a kid and why? ?',
  'If I handed you a plane ticket right now to anywhere in the world, where would you go?',
  'What was your favorite trip you went on?',
  'Road trip or plane trip?',
  'What is your favorite thing to do locally?',
  'If you could either live where it only snows or the temperature never falls below 100 degrees, which would it be?',
  'If you could live in any country, where would you live?',
  'Snow, sand, or other?',
  'You’re going sail around the world. What’s the name of your boat?',
  'If you could have the power of teleportation right now, where would you go and why?',
  'When’s the last time you went somewhere for the first time?',
  'What was the worst injury you ever had?',
  'Tell me an embarrassing story about yourself.?',
  'When did you last cry in front of another person? By yourself?',
  'If you could add a word to the dictionary what would you add and what would it mean?',
  'The zombie apocalypse is coming. Who are three people you want on your team?',
  'If you could choose your age forever, what age would you choose and why?',
  'Teleportation or flying?',
  'If you could be any supernatural creature, what would you be and why?',
  'If you were a vegetable, what vegetable would you be and why?',
  'If you had to lose all your memories, which one would want to lose last?',
  'What are your biggest phobias?',
  'If you were left on a deserted island with either your worst enemy or no one, which would you choose? Why?',
  'What would be the most surprising scientific discovery imaginable? ?',
  'If you could add anyone to Mount Rushmore who would it be and why?',
  'If someone offered you a million dollars to give up your smartphone forever, would you do it?',
  'What’s your cellphone or computer wallpaper? ?',
  'If you could have an unlimited supply of one thing for the rest of your life, what would it be any why?',
  'If you were forced to participate in a flash dance, what song would you perform to and why?',
  'What’s your favorite plant?',
  '116. If you had to be transformed into one household item, what would it be and why?',
  '117. If you could bring back any fashion trend what would it be?',
  '118. If you could get rid of any current trend, what would it be and why?',
  '119. What’s one frequently used word that you can’t stand?',
  '120. What was the first thing you thought about when you woke up this morning? ?',
  '121. If you were a fridge, what item would you hate to hold? What item would you love to hold?',
  '122. If you had to eat a crayon, what color would you choose? Why?',
  '123. Would you show everyone in this meeting your browser history?',
  '124. What’s the most embarrassing thing you ever accidentally messaged to somebody?',
  '125. Have you ever pretended you didn’t see somebody to avoid talking to them?',
  'What is your favorite type of cuisine?',
  'What weird food combinations do you really enjoy?',
  'If you had to eat one meal every day for the rest of your life what would it be and why?',
  'What’s the weirdest food you’ve ever eaten?',
  'How do you like your eggs?',
  'If you had to give up one food forever, what would it be?',
  'What’s something you simply could never eat?',
  'What is something you think is totally overrated?',
  'What’s one piece of advice you wish you’d gotten sooner?',
  'What’s your best scary story?',
  'If you had 25 hours each day, how would you use your extra time?',
  'If you were a wrestler what would be your entrance theme song?',
  'If you were a superhero what would your name be?',
  'If you were a superhero what would your superpower be and why?',
  'What’s the best piece of advice you have ever been given?',
  'What’s the best advice you’ve ever given?',
  'If you could be guaranteed one thing in life (besides money), what would it be?',
  'If you could be the funniest or smartest person in the room, which would you choose?',
  'If extraterrestrials landed on earth and offered to take you with them, would you go?',
  'If extraterrestrials landed on earth, who would you recommend as their first point of contact and why?',
  'If you could go to Mars, would you? Why or why not?',
  'If you were stranded on a desert island, what three items would you want to have with you?',
  'If you could be the world’s best athlete in any sport, which one would it be any why?',
  'How would you describe your sense of humor?',
  'What’s your most-used emoji?',
  'What emoji best describes you?',
  'If you ran the world, what’s one thing you’d change? ?',
  'What would be your campaign slogan if you were running for office?',
  'If you could meet any historical figure, who would you choose and why?',
  'If you had a time machine, would go back in time or into the future?',
  'What was the first thing you bought with your own money?',
  'What was your first car?',
  'If you could live in the 60s, 70s, 80s, or 90s, which would you choose and why?',
  'If you could travel back in time to meet your ancestors or to the future to meet your descendants, which would you pick?',
  'If you could go back in time and pay more attention in one class, what would it be? ?',
  'Are you team Android or team Apple?',
  'Who’s your favorite celebrity?',
  'What book changed your worldview the most?',
  'If you could only watch three movies for the rest of your life, what would they be?',
  'What’s the most recent movie you’ve seen, both at home and in theaters? Would you recommend them?',
  'What TV shows have you been watching lately?',
  'What’s the most bingeable show you’ve ever watched?',
  'What’s your guilty pleasure TV show?',
  'What celebrity do you not like that everyone else loves?',
  'If you could live in any TV show, what would it be?',
  'What book do you bring along on airplanes?',
  'What’s your go-to karaoke song?',
  'What’s your favorite reality TV show?',
  'Which celebrity was your childhood crush?',
  'If you could be friends with any celebrity, who would it be?',
  'If you had an entrance song play every time you entered a room, what would it be?',
  'Which actor or actress do you think deserves an Oscar but doesn’t have one yet?',
  'What album could you listen to over and over again and not get sick of?',
  'What artists have you seen live? Which was the best?',
  'Which musician, alive or dead, do you wish you could see perform?',
  'Have you ever met anyone famous?',
  'What’s your favorite podcast right now?',
  'What’s your favorite animated movie?',
  'Which celebrity has your favorite social media presence?',
  'Who’s your favorite superhero?',
  'What’s the scariest movie you’ve ever seen? Funniest? Saddest?',
  'If you could have lunch with any public figure, dead or alive, who would it be?',
  'What’s your guilty-pleasure song?',
  'What’s your favorite social media platform?',
  'What recent social media trend makes you cringe?',
  'Do you like reality tv shows?',
  'Do you listen to the news?',
  'Spotify or Apple Music?',
  'What was your favorite cartoon show growing up?',
  'Who was the best batman?',
  'Could Jack have fit on the door with Rose in the Titanic?',
  'What’s your favorite Disney movie?',
  'Blue and black dress, or white and gold?',
  'Would you rather have the ability to see 10 minutes into the future or 150 years into the future?',
  'Would you rather be able to swim underwater limitlessly or fly?',
  'Would you rather travel to a beach destination or ski resort?',
  'Would you rather go deep-sea diving or bungee jumping?',
  'Would you rather for your birthday, receive cash or gifts?',
  'Would you rather travel to space or travel to the past?',
  'Would you rather smell with your hands or talk with your feet?',
  'Would you rather go to a house party or a bar?',
  'Would you rather be too hot or too cold?',
  'Would you rather travel by train or travel by plane?',
  'Would you rather trapped in an elevator or stuck on a suspension bridge?',
  'Would you rather be a kid your entire life or be an adult?',
  'Would you rather get a hand-written card or a phone call?',
  'Would you rather hear holiday-themed music forever, or never heard it again?',
  'Would you rather know the answer to every trivia question or the lyric to every song?',
  'Would you rather go for a run or go for a hike?',
  'Would you rather watch a TV show or watch YouTube?',
  'Would you rather be on a survival reality show or dating show?',
  'Would you rather be a detective or a scientist?',
  'Would you rather go to the movie theaters or watch a movie from home?',
  'Would you rather live in a remote destination or the heart of a metropolitan city?',
  'Would you rather have telekinesis (the ability to move things with your mind) or telepathy (the ability to read minds)?',
  'Would you rather be forced to sing along or dance to every single song you hear?',
  'Would you rather be in jail for five years or be in a coma for a decade?',
  'Would you rather be chronically under-dressed or overdressed?',
  'Would you rather have everyone you know be able to read your thoughts or for everyone you know to have access to your Internet history?',
  'Would you rather swim in a pool full of Nutella or a pool full of maple syrup?',
  'Would you rather buy 10 things you don’t need every time you go shopping or always forget the one thing that you need when you go to the store?',
  'Would you rather never be able to go out during the day or never be able to go out at night?',
  'Would you rather always have B.O. and not know it or always smell B.O. on everyone else?',
  'Would you rather spend a week in the forest or a night in a real haunted house?',
  'Would you rather have a pause or a rewind button in your life?',
  'Would you rather always have a full phone battery or a full gas tank?',
  'Would you rather get a paper cut every time you turn a page or bite your tongue every time you eat?',
  'Would you rather be able to take back anything you say or hear any conversation that is about you?',
  'Would you rather have to wear every shirt inside out or every pair of pants backward?',
  'Would you rather travel the world for free for a year or have $50,000 to spend however you please?',
  'Would you rather be in a zombie apocalypse or a robot apocalypse?',
  'Would you rather give up your cellphone for a month or bathing for a month?',
  'Would you rather lose the ability to read or lose the ability to speak?',
  'Would you rather be always stuck in traffic but find a perfect parking spot or never hit traffic but always take forever to park?',
  'Would you rather have to wear sweatpants everywhere for the rest of your life or never wear sweatpants again?',
  'Would you rather detect every lie you hear or get away with every lie you tell?',
  'Would you rather listen to your least favorite song on a loop for a year or never listen to any music at all for a year?',
  'Would you rather win the lottery but have to spend it all in one day or triple your current salary forever?',
  'If you had to be transformed into one household item, what would it be and why?',
  'Would you rather be able to run at 100 miles per hour or fly at 10 miles per hour?',
  'Would you rather live without heat and AC or live without social media?',
  'If you could instantly learn a new talent, what would it be?',
  'Do you play video games?',
  'What’s your favorite hobby right now? What’s a hobby you’ve always wanted to take up?',
  'Can you play any instruments? If not, what do you wish you could play?',
  'What is your favorite thing to do by yourself?',
  'What is your favorite sport or physical activity?',
  'What crazy activities do you dream of trying someday?',
  'What is your idea of fun?',
  'What two things do you consider yourself to be very good at?',
  'What two things do you consider yourself to be very bad at?',
  'If money and time were no object, what would you be doing right now?',
  'What is something you hate doing? Why?',
  'What is something you love doing? Wh?',
  'Do you have any hidden talents? What can you do?',
  'What was one new experience you tried that was completely unknown or uncomfortable to you at the time you tried it?',
  'Is soap clean or dirty?',
  'Is a hotdog a sandwich?',
  'Why do people say “slept like a baby” when babies wake up all the time in the middle of the nigh?',
  'If a turtle doesn’t have a shell, is it homeless or naked?',
  'Is water wet?',
  'Do you eat rice with a spoon or a fork?',
  'Is a thumb a finger?',
  'Is cereal a soup?',
  'Should pineapple go on pizza?',
  'Is GIF pronounced gift (with a silent “t”) or jif (like the peanut butter)?',
  'Are noodles pasta?',
  'Are tomatoes a fruit?',
  'How many holes does a straw have?',
  'Is cheesecake a cake or a pie?',
  'Which letter is silent in the word “scent”, the “s” or the “c”?',
  'Are bacon bits a seasoning?',
  'Should you recline your seat on a flight?',
  'If tomato is a fruit, is ketchup a jam?',
  'How deep does a pan have to be before it is considered a pot?',
  'Should toilet paper be hung over or under?',
  'Is a fritter a donut?',
  'What color are mirrors?',
  'Why is it called quick sand if you sink slowly in it?',
  'If you mix dirt and water, are you making water dirty or dirt wet?',
  'If a tree falls in the woods and nothing is there to hear it, did it make a sound?',
  'Does the person flying in the middle seat get both armrests?',
  'Are dogs’ front limbs arms or legs?',
  'Why do we say pair of paints, when it’s just one article of clothing?',
  'Is Die Hard a Christmas movie?',
  'If you had to choose only one holiday to celebrate each year, which would it be any whyu?',
  'What’s your favorite holiday?',
  'What’s your favorite childhood holiday tradition?',
  'What’s your favorite holiday movie?',
  'Who’s the toughest person you have to buy for during the holidays?',
  'What’s your favorite—or least favorite—holiday song?',
  'If someone gifted you a gift card to any store, where would you want it to be for?',
  'If you could travel anywhere for a holiday, where would it be and why?',
  'What’s the best gift you’ve ever given anyone? What’s the worst?',
  'What do you do when you get a holiday gift you hate?',
]
